### ISSUE TITLE
Variable "CONTRACT_ID" does not exist in this scope.

### ISSUE THREAD

**Issue by SilentCicero** [FuelLabs/sway-vscode-plugin#154] opened 2023-05-24 09:34 UTC
The VSCode plugin incorrectly highlights the given CONTRACT_ID identifier as invalid, when it is valid Sway for testing.

<img width="766" alt="Screen Shot 2023-05-24 at 10 32 20 AM" src="https://github.com/FuelLabs/sway-vscode-plugin/assets/9806174/43307932-f4a4-46a8-abf8-b78ecc916ef7">

**Comment by JoshuaBatty** [comment] 2023-07-03 01:39
Looking into this now. 

Calling `forc build` on this example doesn't produce any warnings about an unused variable.

```
Joshuas-Mac-Studio% forc build
 Compiling library core (/Users/josh/.forc/git/checkouts/std-9be0d6062747ea7/0d45b890c9eaa75b88093a9a4cbecbf5ca8c0731/sway-lib-core)
 Compiling library std (git+https://github.com/fuellabs/sway?tag=v0.41.0#0d45b890c9eaa75b88093a9a4cbecbf5ca8c0731)
 Compiling contract contract_id_unused (/Users/josh/Documents/rust/fuel_test_projects/contract_id_unused)
  Finished debug in 1.020239208s
  contract contract_id_unused
      Bytecode size: 60 bytes
```

Yet, if we inspect the diagnostics that are returned to the LSP we can see that we are getting a warning sent from the compiler for `CONTRACT_ID`

```
[Trace - 10:01:02] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "diagnostics": [
        {
            "message": "Variable \"CONTRACT_ID\" does not exist in this scope.",
            "range": {
                "end": {
                    "character": 44,
                    "line": 14
                },
                "start": {
                    "character": 33,
                    "line": 14
                }
            },
            "severity": 1
        }
    ],
    "uri": "file:///Users/josh/Documents/rust/fuel_test_projects/contract_id_unused/src/main.sw"
}
```

Looking into the compiler, the `Variable \"{}\" does not exist in this scope` error is emitted when resolving symbols in the `namespace` within the `type_check_variable_expression` function. If the symbol can't be found in the namespace then the compiler throws a `CompileError::UnknownVariable` error which we see above. 

So the problem is that `CONTRACT_ID` is a special constant that is injected into the namespace from `forc_pkg::build()`. In the language server we call `forc_pkg::check()` as we only need to produce abstract syntax trees from the compiler and not build byte code. Because byte code is not produced, `forc_pkg` is unable to produce a value for `CONTRACT_ID` and this it's symbol is not injected into the compilers namespace, leading the the `CompileError::UnknownVariable`. 

AFAIK this is the only symbol that is injected into the namespace from outside of the compiler. As such, we can filter out `UnknownVariable` warnings in the language server if the name ==  `CONTRACT_ID`.

**Closed** 2023-07-05 13:32 UTC
Labels: bug
