### ISSUE TITLE
 The Sway Language Server server crashed 5 times in the last 3 minutes 

### ISSUE THREAD

**Issue by chlenc** [FuelLabs/sway-vscode-plugin#112] opened 2023-01-04 19:36 UTC
Hey guys!!!
I have run into a problem with the language server, autoformat does not work 

My code you can find it here
https://github.com/sway-gang/sway-lend/blob/master/contracts/market/src/main.sw

To open the file you can use these commands
```
git clone https://github.com/sway-gang/sway-lend
cd sway lend
git checkout
git checkout fe2508784f7dc11e6878dfd83136b81cb52e2701   
code ./contracts/market/src/main.sw
```

Here is screenshot
<img width="490" alt="image" src="https://user-images.githubusercontent.com/35231749/210634070-5ecb32c8-cbdb-453f-a74b-068df7ce1c7b.png">

Sway language server output
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Char index out of bounds: char index 32982, Rope/RopeSlice char length 32749', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/ropey-1.5.0/src/rope.rs:345:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 1:54:55 PM] Connection to server got closed. Server will restart.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Char index out of bounds: char index 32982, Rope/RopeSlice char length 32749', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/ropey-1.5.0/src/rope.rs:345:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 1:54:59 PM] Connection to server got closed. Server will restart.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Char index out of bounds: char index 32982, Rope/RopeSlice char length 32749', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/ropey-1.5.0/src/rope.rs:345:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 1:55:30 PM] Connection to server got closed. Server will restart.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Char index out of bounds: char index 32982, Rope/RopeSlice char length 32749', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/ropey-1.5.0/src/rope.rs:345:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 5:39:30 PM] Connection to server got closed. Server will restart.
```

Sway LSP Client output
```
INFO [1/4/2023, 7:27:10 PM]: Starting the Sway Language Client and Server
INFO [1/4/2023, 7:27:10 PM]: Extension version: 0.2.7
INFO [1/4/2023, 7:27:10 PM]: Using configuration {
  trace: {
    server: 'off',
    extension: false,
    'fuel-core': { logfile: '/tmp/fuel-core_sway-vscode-plugin.log' }
  },
  debug: { showCollectedTokensAsWarnings: 'off' },
  logging: { level: 'error' },
  inlayHints: { renderColons: true, typeHints: true, maxLength: 25 }
}
INFO [1/4/2023, 7:27:10 PM]: Client has Connected to the Sway Language Server Successfully!
INFO [1/4/2023, 7:27:10 PM]: Starting the Sway Language Client and Server
INFO [1/4/2023, 7:27:10 PM]: Extension version: 0.2.7
INFO [1/4/2023, 7:27:10 PM]: Using configuration {
  trace: {
    server: 'off',
    extension: false,
    'fuel-core': { logfile: '/tmp/fuel-core_sway-vscode-plugin.log' }
  },
  debug: { showCollectedTokensAsWarnings: 'off' },
  logging: { level: 'error' },
  inlayHints: { renderColons: true, typeHints: true, maxLength: 25 }
}
```

I think perhaps the server is disturbed by the logo, which is located on lines 3-10

**Comment by JoshuaBatty** [comment] 2023-01-04 22:12
Hi @chlenc thanks for reporting this. I just checked out your commit following the steps you posted above. The language server seems to be running fine for me. 

Can I ask what version of `forc lsp` you have installed? See below for my installed version:

```
forc lsp --version
forc-lsp 0.32.2
```

**Comment by Rodarus** [comment] 2023-01-16 09:13
Hi @JoshuaBatty, I'm also running into this issue in the last few days and i have version 0.31.1 installed. I will update and let you know if that fixes it for me.

**Comment by JoshuaBatty** [comment] 2023-01-16 09:17
Thanks @Rodarus. Please let us know how it goes after updating.

**Comment by Rodarus** [comment] 2023-01-17 06:41
The issue still persists for me.

I ran "forc update -d lsp" but it's still at 0.31.1; did i miss something?

This is the error:
[Info  - 7:29:04 AM] Connection to server got closed. Server will restart.
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', sway-parse/src/parser.rs:33:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Error - 7:29:04 AM] The Sway Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.

**Comment by JoshuaBatty** [comment] 2023-01-17 09:35
I would recommend installing forc and i's plugins (include LSP) using `fuelup`. 

Then to update, you just need to run `fuelup self update`.

Feel free to see [this guide](https://fuellabs.github.io/fuelup/master/installation/index.html)

In the meantime, if you want to send me a link to your project that's causing the error I can see if I can find what the cause is.

**Comment by JoshuaBatty** [comment] 2023-07-02 23:40
Hey @Rodarus just checking in to see if you got everything working? Will close this issue if so. Thanks.

**Comment by JoshuaBatty** [comment] 2023-07-11 00:55
closing as the issue has become inactive.

**Closed by JoshuaBatty** 2023-07-11 00:55 UTC
