### ISSUE TITLE
Slow plugin

### ISSUE THREAD

**Issue by PaulZhemanov** [FuelLabs/sway-vscode-plugin#172] opened 2024-03-25 10:43 UTC
Hi guys! I'm having trouble getting the plugin to work correctly. It works so slowly. I need correct autocomplete, go to definition, hinting of function signature and arguments. Help me please.

```
forc-lsp 0.49.3
```

**Comment by JoshuaBatty** [comment] 2024-03-25 22:16
Hi Paul, I'm happy to look into this for you. Do you have a specific project I might be able to reproduce with?

**Comment by PaulZhemanov** [comment] 2024-03-26 10:10
> Hi Paul, I'm happy to look into this for you. Do you have a specific project I might be able to reproduce with?

Hi! Can you send twitter nickname?

**Comment by PaulZhemanov** [comment] 2024-03-26 10:11
> > Hi Paul, I'm happy to look into this for you. Do you have a specific project I might be able to reproduce with?
> 
> Hi! Can you send telegram nickname?

@JoshuaBatty

**Comment by chlenc** [comment] 2024-03-27 10:40
Shared the spark access 🫡
@JoshuaBatty @PaulZhemanov 
https://github.com/compolabs/spark-perps/invitations

**Comment by JoshuaBatty** [comment] 2024-03-27 10:46
Received thanks guys. I'll start doing some profiling over the next week.

**Comment by PaulZhemanov** [comment] 2024-03-28 09:10
> Received thanks guys. I'll start doing some profiling over the next week.

@JoshuaBatty this "loading" appears very often and hinders development, 
<img width="505" alt="image" src="https://github.com/FuelLabs/sway-vscode-plugin/assets/133055914/daad2ed1-2621-47b6-b2e1-ff30edf71413">

**Comment by PaulZhemanov** [comment] 2024-04-01 18:14
@JoshuaBatty Hello. The plugin is terrible..  I compile my contract with no errors and see this in my editor... 
![IMAGE 2024-04-01 21:12:56](https://github.com/FuelLabs/sway-vscode-plugin/assets/133055914/d2f63d22-bd5b-47bd-aa60-bf48ca26f010)
A plugin should speed up development, not slow it down. Please fix it.

**Comment by JoshuaBatty** [comment] 2024-04-02 00:38
Hi @PaulZhemanov please be aware of the issue and that we are working on this as a priority. We will hopefully have a fix soon. The TLDR of the issue is the compiler is crashing due to the garbage collector not working properly for certain types. When this happens it also crashed the server plugin, leading to the screenshots. Reloading the window will allow it to work again until the next time the GC <> compiler become out of sync. Obviously this is very frustrating for users and we are looking into a fix.

**Comment by JoshuaBatty** [comment] 2024-04-02 05:05
If you want a quick fix you could checkout my `josh/storage_gc_test` branch on the sway repo and change [this line](https://github.com/FuelLabs/sway/pull/5813/files#diff-15df12ff5d488db76f2e268763375bca3291d907060eee4cdbce032da02d3185R69) from true to false `gc_enabled: false,`

then run `cargo install --path ./forc-plugins/forc-lsp` to install a local copy of the language server. Because the garbage collector is disabled you'll probably want to reload the editor when the RAM usage gets too high but it should at least get rid of the crash for now while we investigate the root cause.

**Comment by JoshuaBatty** [comment] 2024-04-15 01:34
Hey @chlenc & @PaulZhemanov we have fixed the Garbage collector and LSP issues. This has been merged and is in the latest 0.54 release. It's still going to be slow to respond due to the lack of granular caching and the size of your workspace, but it shouldn't be crashing and become non-responsive now. We're now looking at further optimisations.

**Comment by chlenc** [comment] 2024-04-22 11:53
gm guys thank you!!

Btw is it possible to somehow disable reentrancy warnings?

**Comment by chlenc** [comment] 2024-04-22 16:24
<img width="993" alt="image" src="https://github.com/FuelLabs/sway-vscode-plugin/assets/35231749/51caee50-a453-480d-ae10-bd479fd8d882">

**Comment by chlenc** [comment] 2024-04-25 12:00
@JoshuaBatty

**Comment by JoshuaBatty** [comment] 2024-04-25 23:10
Sorry i've been out sick this week. We don't off the ability to disable certain warning types but we could look at adding that in the future. I'll take a closer look at this next week and see what we might be able to do.

**Comment by PaulZhemanov** [comment] 2024-05-02 13:52
Hi @JoshuaBatty . I got this notification and plugin doesnt work.
<img width="406" alt="image" src="https://github.com/FuelLabs/sway-vscode-plugin/assets/133055914/68dc9a42-2f2a-4cf0-b6ed-8a80db4f9654">

**Comment by PaulZhemanov** [comment] 2024-05-03 18:13
Hi @JoshuaBatty . how can I disable these settings 


> If you want a quick fix you could checkout my `josh/storage_gc_test` branch on the sway repo and change [this line](https://github.com/FuelLabs/sway/pull/5813/files#diff-15df12ff5d488db76f2e268763375bca3291d907060eee4cdbce032da02d3185R69) from true to false `gc_enabled: false,`
> 
> then run `cargo install --path ./forc-plugins/forc-lsp` to install a local copy of the language server. Because the garbage collector is disabled you'll probably want to reload the editor when the RAM usage gets too high but it should at least get rid of the crash for now while we investigate the root cause.

Hi @JoshuaBatty . how can I disable these settings

**Comment by JoshuaBatty** [comment] 2024-05-06 02:14
Hi Paul what version of forc-lsp are you using?

The garbage collection issue has been resolved and is in the latest release.

**Comment by mpoplavkov** [comment] 2024-05-06 12:39
> Hey @chlenc & @PaulZhemanov we have fixed the Garbage collector and LSP issues. This has been merged and is in the latest 0.54 release. It's still going to be slow to respond due to the lack of granular caching and the size of your workspace, but it shouldn't be crashing and become non-responsive now. We're now looking at further optimisations.

Hey @JoshuaBatty, how to update forc-lsp to 0.54 if I'm using the `beta-5` channel?

**Comment by PaulZhemanov** [comment] 2024-05-07 08:17
@JoshuaBatty forc-lsp 0.49.3

**Comment by JoshuaBatty** [comment] 2024-05-07 10:04
I would suggest the quickest way to get it working would be to checkout the sway repo and follow the below commands to get the server updated.

```
git checkout https://github.com/FuelLabs/sway
cd sway
cargo install --path ./forc-plugins/forc-lsp
```

then running the `which forc-lsp` you should see something like.  

```
 ~  which forc-lsp                                                                                           
/Users/joshuabatty/.cargo/bin/forc-lsp

 ~  forc-lsp --version                                                                                  
forc-lsp 0.55.0
```

**Comment by chlenc** [comment] 2024-05-07 19:27
<img width="1186" alt="image" src="https://github.com/FuelLabs/sway-vscode-plugin/assets/35231749/02a95431-b3fe-4e5f-bcf4-e000a0050cc6">

hope plugin will be better soon

**Comment by chlenc** [comment] 2024-05-09 14:50
Gm guys 

@JoshuaBatty @arboleya 

Are there any updates??

**Comment by JoshuaBatty** [comment] 2024-05-10 03:53
The main issue here is that our compiler is slow and we lack a caching system to support more incremental compilation. We are focusing on improving compilation speeds at the moment, in-fact we have merged 3 PR's in the past 24 hours that have improved compilation speeds by ~60%. We are also in the process of putting together a design for implementing more granular caching. Unfortunately, until the compiler is optimised and caching support is implemented then the language server performance is going to be sluggish on large projects like the spark repo. I'll keep you updated as we go.

**Comment by JoshuaBatty** [comment] 2024-08-19 01:06
Another update, we now have support for caching at the file level rather than the previous project level. This should speed up response times substantially for projects with lots of files. We have plans to enable caching at the AST node level but this should be a nice bridge in the meantime.

**Comment by JoshuaBatty** [comment] 2024-10-28 00:40
I'm going to close this issue in favour of this tracking issue in the sway repo. https://github.com/FuelLabs/sway/issues/6230

**Closed by JoshuaBatty** 2024-10-28 00:40 UTC
